// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcuYbtDHrsVpv5yiIOZlpgkhvl56HnJXM',
    appId: '1:618998045480:web:199535dac88c01a282ce1d',
    messagingSenderId: '618998045480',
    projectId: 'asha-triage',
    authDomain: 'asha-triage.firebaseapp.com',
    storageBucket: 'asha-triage.firebasestorage.app',
    measurementId: 'G-W1BF0KQBDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAHH_qerhIZf7QJFGDYT5aTLSwNJRWAAY',
    appId: '1:618998045480:android:1ef44c5c32a1127e82ce1d',
    messagingSenderId: '618998045480',
    projectId: 'asha-triage',
    storageBucket: 'asha-triage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCswRxJxnnG_xeMgmivZLgVFCcxchRvR7U',
    appId: '1:618998045480:ios:a5d63a189943d4ad82ce1d',
    messagingSenderId: '618998045480',
    projectId: 'asha-triage',
    storageBucket: 'asha-triage.firebasestorage.app',
    iosBundleId: 'com.example.aiPulseTriage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCswRxJxnnG_xeMgmivZLgVFCcxchRvR7U',
    appId: '1:618998045480:ios:a5d63a189943d4ad82ce1d',
    messagingSenderId: '618998045480',
    projectId: 'asha-triage',
    storageBucket: 'asha-triage.firebasestorage.app',
    iosBundleId: 'com.example.aiPulseTriage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcuYbtDHrsVpv5yiIOZlpgkhvl56HnJXM',
    appId: '1:618998045480:web:3d8197f1c78c489782ce1d',
    messagingSenderId: '618998045480',
    projectId: 'asha-triage',
    authDomain: 'asha-triage.firebaseapp.com',
    storageBucket: 'asha-triage.firebasestorage.app',
    measurementId: 'G-V1VB0Z82Q3',
  );
}
